import { Id } from "@/convex/_generated/dataModel";

export type Agent = {
    _id: Id<"agentTable">;        // Convex internal ID
    _creationTime: number;        // Auto-generated by Convex
    agentId: string;              // Your UUID for routing
    agentName: string;
    userId: Id<"userTable">;
    nodes?: any;
    edges?: any;
    published: boolean;
    createdAt: number;            // Your manual timestamp
    config: any; 
    agentToolConfig?: any;         // Typed config instead of 'any'
}
